function display_settings(settings)
%DISPLAY_SETTINGS Print-out a summary of the simulation settings
    disp('-----')
    disp(['Running meta-analysis simulations on ' ...
        mat2str(settings.ks) ' studies'])
    disp(['    Between-study variance = ' mat2str(settings.btw_sigmas)])
    disp(['    Within-study variance = ' mat2str(settings.wth_sigmas)])
    disp(['    Variations of within-study variance across studies = ' ...
        mat2str(settings.wth_sigma_variations)])
    disp(['    Constant number of subjects per study = ' ...
        mat2str(settings.wth_sigma_sames)])
    disp(['    Proportion of studies computed with another software = '...
        mat2str(settings.soft_props)])
    disp(['    Unit factor for the other software = '...
        mat2str(settings.soft_factors)])
    disp(['    Unit mismatches = ['...
        strjoin(settings.unit_mismatches, ', ') ']'])    
    disp(['    Type of analysis (1/one-sample, 2/two-sample,' ...
        ' 3/two-sample unbalanced) = '...
        mat2str(settings.analysis_types)])        
    disp(['    Image size (in every direction) = '...
        mat2str(settings.iter_onedir)])    
    disp(['    Total number of simulations per iteration = '...
        mat2str(settings.nsimu)])        
    disp('')
    disp(['    Permutations computed with ' ...
        num2str(settings.nperm) ' permutations.'])          
    disp('-----')
    disp('')
end

